title: "BioPhotonics Lab"
author: "Soraya Caixeiro"
description: "University of Bath"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "Aboutme.md", title: "About me"}
  - {file: "news.html", title: "News"}
  - {file: "People.md", title: "People"}
  - {file: "Pub.html", title: "Publications"}
  - {file: "vacancy.md", title: "Vacancies"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:scc201@bath.ac.uk"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/sorayacaixeiro"}
  - {title: OrcidID, icon: orcid, url: "https://orcid.org/0000-0003-4605-957X"}  
  - {title: Google scholar, icon: graduation-cap, url: "https://scholar.google.co.uk/citations?user=9EDbO-wAAAAJ&hl=en" }
  - {title: University, icon: building, url: "https://researchportal.bath.ac.uk/en/persons/soraya-caixeiro" }
  - {title: Github, icon: github, url: "https://github.com/sorayacaixeiro"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
